### ISSUE TITLE
新版问题

### ISSUE THREAD

**Issue by 0honus0** [ehForwarderBot/efb-qq-slave#73]
用的IOTBot 客户端
1.把qq群组绑定到别的tg群组后，如果重启efb-qq-slave后端，有时在分流的tg群组中生成chat会出错
提示:
EFB Telegram 主端遇到错误 Entity id should be a string, XXXXXXXXXX found.

2.可以接受，新生成会话无法发送消息。提示(Message is not sent. IndexError('list index out of range'))。日志显示:

Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fefb46b5b70>
    └ <Thread(ThreadPoolExecutor-0_41, started daemon 140666419934976)>
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fefb46b5950>
    └ <Thread(ThreadPoolExecutor-0_41, started daemon 140666419934976)>
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_41, started daemon 140666419934976)>
    │    │        │    └ (<weakref at 0x7fef9c7b8868; to 'WorkerPool' at 0x7fefaec35470>, <_queue.SimpleQueue object at 0x7fefaec26ae8>, None, ())
    │    │        └ <Thread(ThreadPoolExecutor-0_41, started daemon 140666419934976)>
    │    └ <function _worker at 0x7fefb101e1e0>
    └ <Thread(ThreadPoolExecutor-0_41, started daemon 140666419934976)>
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fefb101e2f0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fef9c16c320>
> File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fef9c16c320>
             │    │   │    └ (<botoy.model.GroupMsg object at 0x7fef9c1df470>,)
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fef9c16c320>
             │    └ <function iot.__init__.<locals>.on_group_msg at 0x7fefaec2fae8>
             └ <concurrent.futures.thread._WorkItem object at 0x7fef9c16c320>

  File "/usr/local/lib/python3.7/dist-packages/efb_qq_plugin_iot/IOTBot.py", line 123, in on_group_msg
    messages.extend(func(ctx))
    │        │      │    └ <botoy.model.GroupMsg object at 0x7fef9c1df470>
    │        │      └ <function IOTMsgProcessor.iot_AtMsg_group at 0x7fefaec20d90>
    │        └ <method 'extend' of 'list' objects>
    └ []

TypeError: 'NoneType' object is not iterable  

第二条可能是qq异地登陆风控，无法在群组回复。下面的错误信息 具体不清楚

**Comment by Sosueyakiko** [comment]
我用mirai http模式也没办法向QQ群发消息  是不是也是异地风控啊 请问这个怎么办呀
@milkice233

**Comment by 0honus0** [comment]
> 我用mirai http模式也没办法向QQ群发消息 是不是也是异地风控啊 请问这个怎么办呀
> @milkice233

能向私人发消息不，能的话应该就是风控了，过一段时间就好

**Comment by Sosueyakiko** [comment]
> > 我用mirai http模式也没办法向QQ群发消息 是不是也是异地风控啊 请问这个怎么办呀
> > @milkice233
> 
> 能向私人发消息不，能的话应该就是风控了，过一段时间就好

噢噢这样啊  谢谢大佬
