### ISSUE TITLE
发送图片bug与功能请求

### ISSUE THREAD

**Issue by 0honus0** [ehForwarderBot/efb-qq-slave#80]
从tg发送图片这个功能有的时候发出去的图有问题，在qq端会无法查看，暂时解决方法是每日重启
功能请求是发送文件功能，希望可以直接从tg端发文件

**Comment by milkice233** [comment]
前者我注意到了这个现象，但是目前不确定是 mirai 在处理图片上有问题还是上传文件到腾讯服务器的时候失败
对于功能请求，IOT/mirai 都暂时不支持直接发送文件
